version: "3.9"
   
services:
  db:
    container_name: blogmedia-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=blogmedia-db
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev

  app:
    container_name: blogmedia-app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    env_file:
      .env

  web:
    container_name: blogmedia-web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - './web:/web'
      - '/web/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  # frontend
volumes:
  data: